version: "3.7"

services:
  api:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    volumes:
      - ../src:/usr/app/src
      - ../nodemon.json:/usr/app/nodemon.json
    container_name: budgie-api
    environment:
      - PORT=4000
    expose:
      - 4000
      - 9229
    ports:
      - 4000:4000
      - 9229:9229
