version: "3.7"

services:
  budgie-api:
    build:
      context: ../
      dockerfile: docker/Dockerfile.prod
      container_name: budgie-api
    environment:
      - PORT=4000
    expose:
      - 4000
    ports:
      - 4000:4000
